version: "3"

services:
  carberat_postgresql:
    image: postgres:12
    container_name: carberat_postgresql
    volumes:
      - carberat_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - carberat_network

volumes:
  carberat_postgresql:
    external: true
networks:
  carberat_network:
    external: true