version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - carberat_static_volume:/backend/static
      - carberat_media_volume:/backend/media
    networks:
      - nginx_network

volumes:
  carberat_static_volume:
    external: true
  carberat_media_volume:
    external: true
networks:
  nginx_network:
    external: true